export default function applicationTypes() {
  return {
    SET_WALLET_ADDRESS: 'SET_WALLET_ADDRESS',
    SET_WEB3: 'SET_WEB3',
    SET_DEFAULT_REFERRER: 'SET_DEFAULT_REFERRER',
    SET_BNB_BALANCE: 'SET_BNB_BALANCE',
    SET_TOKEN_BALANCE: 'SET_TOKEN_BALANCE',
    SET_DEPOSIT_DATA: 'SET_DEPOSIT_DATA',
    SET_IS_NEED_TO_UPDATE: 'SET_IS_NEED_TO_UPDATE',
    SET_IS_DEPOSIT_TRANSACTION: 'SET_IS_DEPOSIT_TRANSACTION',
    SET_IS_WITHDRAW_TRANSACTION: 'SET_IS_WITHDRAW_TRANSACTION',
    SET_NOT_CORRECT_CHAIN: 'SET_NOT_CORRECT_CHAIN',
    SET_REDIRECT_TO: 'SET_REDIRECT_TO',
    SET_TOAST_DATA: 'SET_TOAST_DATA'
  }
}
