export default function accountTypes() {
  return {
    SET_TOTAL_DASHBOARD_STATISTICS: 'SET_TOTAL_DASHBOARD_STATISTICS',
    SET_PERSONAL_DASHBOARD_STATISTICS: 'SET_PERSONAL_DASHBOARD_STATISTICS',
    SET_PERSONAL_BONUSES_STATISTICS: 'SET_PERSONAL_BONUSES_STATISTICS',
    SET_LEADER_PERSONAL_INFO: 'SET_LEADER_PERSONAL_INFO',
    SET_LEADER_PROGRESS_DATA: 'SET_LEADER_PROGRESS_DATA',
    SET_USER_INFO: 'SET_USER_INFO',
    SET_CONTRACT_INFO: 'SET_CONTRACT_INFO'
  }
}
